### ISSUE TITLE
I cannot get a refresh token

### ISSUE THREAD

**Issue by s1534** [adn77/alexa-cookie-cli#5]
When running alexa-cookie-cli-macos-x64 on mac os CLI, I cannot get a refresh token.

Atza|... is able to get the refresh token.

What should I do?

**Comment by Apollon77** [comment]
> What should I do?

First of all please provide more information. I do not understand what you try to say.

Please add example output and and and

**Comment by s1534** [comment]
I want to use [alexa-remote-control ](https://github.com/thorsten-gehrig/alexa-remote-control)
It says here that I need to enter a refresh token, so I running alexa-cookie-cli-macos-x64 on mac os CLI
`./alexa-cookie-cli-macos-x64 -b amazon.co.jp
`
output
```
Error: You can try to get the cookie manually by opening http://localhost:8080/ with your browser. / null
null / "ubid-main=; session-id=; csm-hit=; ubid-acbjp=; x-acbjp=; at-acbjp=Atza|; frc=; map-md=; session-token="
```
However, it appears that no refresh tokens are output here.

**Comment by Lyve1981** [comment]
Its now failing for me too, even though I successfully used amazon-remote-control for years.

My guess is that this is due to changes on Amazon site. alexa.amazon.de now displays a QR code only that you have to scan with your phone to open/install the Alexa App, the "old" web page seems to be deprecated.

I am not sure if I should post the full issue here or in the remote control repo, so here it goes:

I am getting the "login failed, maybe you get a captcha" thing on ARC, however, the webpage /tmp/.alexa.login is not a captcha but "this site does not exist" response, assuming Amazon changed something on their end.

If I try the new cookie approach with a binary of this repo (which didn't exist at the time I set up ARC), I get the same message in the CLI as @s1534 and if I open http://localhost:8080/, the only thing I see is the new Amazon QR code page that wants me to install Alexa on my phone. If I click the "Back to previous version of localhost:8080" at the top, I get an ERR_CONNECTION_REFUSED, which is understandable as I assume the proxy is very simple and doesn't support redirects etc.

**Comment by adn77** [comment]
@patrik72 if you get that error, the **REFRESH_TOKEN** variable is not set (with the token retrieved from *alexa-cookie-cli*)

@Lyve1981 what is your Amazon country domain. I just tried amazon.de and was able to login successfully and retrieved a new refresh-token.

**Comment by adn77** [comment]
@s1534 sorry for the app not working for you. If you're able to run a nodeJS container, you should give @Apollon77's original app a try: https://github.com/Apollon77/alexa-cookie

**Comment by weboo** [comment]
After making this modification, it works for me.

package.json
```
  "dependencies": {
-    "alexa-cookie2": "^4.0.1",
+    "alexa-cookie2": "^4.1.3",
```

**Comment by adn77** [comment]
please checkout the latest version and make sure to use an IP address (e.g. 127.0.0.1) to listen on instead of "localhost"
